2024-05-02 17:31:14,525 INFO    StreamThr :94266 [internal.py:wandb_internal():87] W&B internal server running at pid: 94266, started at: 2024-05-02 17:31:14.525367
2024-05-02 17:31:14,527 DEBUG   HandlerThread:94266 [handler.py:handle_request():144] handle_request: status
2024-05-02 17:31:14,529 INFO    WriterThread:94266 [datastore.py:open_for_write():85] open: /root/Project-Build-an-ML-Pipeline-Starter/src/data_check/wandb/run-20240502_173114-4ylu9rl0/run-4ylu9rl0.wandb
2024-05-02 17:31:14,530 DEBUG   SenderThread:94266 [sender.py:send():334] send: header
2024-05-02 17:31:14,535 DEBUG   SenderThread:94266 [sender.py:send():334] send: run
2024-05-02 17:31:14,536 INFO    SenderThread:94266 [sender.py:_maybe_setup_resume():721] checking resume status for None/nyc_airbnb/4ylu9rl0
2024-05-02 17:31:15,496 ERROR   SenderThread:94266 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 17:31:15,496 ERROR   SenderThread:94266 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 17:31:16,782 ERROR   SenderThread:94266 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 17:31:16,782 ERROR   SenderThread:94266 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 17:31:19,536 DEBUG   HandlerThread:94266 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:31:19,556 ERROR   SenderThread:94266 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 17:31:19,556 ERROR   SenderThread:94266 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 17:31:19,556 INFO    SenderThread:94266 [retry.py:__call__():169] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 128, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 241, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-05-02 17:31:24,034 ERROR   SenderThread:94266 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 17:31:24,034 ERROR   SenderThread:94266 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 17:31:24,537 DEBUG   HandlerThread:94266 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:31:29,538 DEBUG   HandlerThread:94266 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:31:32,554 ERROR   SenderThread:94266 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 17:31:32,555 ERROR   SenderThread:94266 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 17:31:34,540 DEBUG   HandlerThread:94266 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:31:39,541 DEBUG   HandlerThread:94266 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:31:44,542 DEBUG   HandlerThread:94266 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:31:49,543 DEBUG   HandlerThread:94266 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:31:50,143 ERROR   SenderThread:94266 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 17:31:50,143 ERROR   SenderThread:94266 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 17:31:54,545 DEBUG   HandlerThread:94266 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:31:59,546 DEBUG   HandlerThread:94266 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:32:04,547 DEBUG   HandlerThread:94266 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:32:09,548 DEBUG   HandlerThread:94266 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:32:14,549 DEBUG   HandlerThread:94266 [handler.py:handle_request():144] handle_request: cancel
2024-05-02 17:32:14,551 DEBUG   HandlerThread:94266 [handler.py:handle_request():144] handle_request: cancel
2024-05-02 17:32:14,551 DEBUG   SenderThread:94266 [sender.py:send():343] Record cancelled: run
2024-05-02 17:32:14,552 DEBUG   HandlerThread:94266 [handler.py:handle_request():144] handle_request: status_report
2024-05-02 17:32:16,931 DEBUG   HandlerThread:94266 [handler.py:handle_request():144] handle_request: shutdown
2024-05-02 17:32:16,931 INFO    HandlerThread:94266 [handler.py:finish():841] shutting down handler
2024-05-02 17:32:17,552 INFO    SenderThread:94266 [sender.py:finish():1491] shutting down sender
2024-05-02 17:32:17,552 INFO    WriterThread:94266 [datastore.py:close():299] close: /root/Project-Build-an-ML-Pipeline-Starter/src/data_check/wandb/run-20240502_173114-4ylu9rl0/run-4ylu9rl0.wandb
