2024-05-02 17:29:59,439 INFO    StreamThr :93883 [internal.py:wandb_internal():87] W&B internal server running at pid: 93883, started at: 2024-05-02 17:29:59.438274
2024-05-02 17:29:59,440 DEBUG   HandlerThread:93883 [handler.py:handle_request():144] handle_request: status
2024-05-02 17:29:59,442 INFO    WriterThread:93883 [datastore.py:open_for_write():85] open: /root/Project-Build-an-ML-Pipeline-Starter/src/data_check/wandb/run-20240502_172959-4ylu9rl0/run-4ylu9rl0.wandb
2024-05-02 17:29:59,443 DEBUG   SenderThread:93883 [sender.py:send():334] send: header
2024-05-02 17:29:59,449 DEBUG   SenderThread:93883 [sender.py:send():334] send: run
2024-05-02 17:29:59,451 INFO    SenderThread:93883 [sender.py:_maybe_setup_resume():721] checking resume status for None/nyc_airbnb/4ylu9rl0
2024-05-02 17:30:00,395 ERROR   SenderThread:93883 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 17:30:00,395 ERROR   SenderThread:93883 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 17:30:01,644 ERROR   SenderThread:93883 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 17:30:01,644 ERROR   SenderThread:93883 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 17:30:04,258 ERROR   SenderThread:93883 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 17:30:04,258 ERROR   SenderThread:93883 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 17:30:04,258 INFO    SenderThread:93883 [retry.py:__call__():169] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 128, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 241, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-05-02 17:30:04,451 DEBUG   HandlerThread:93883 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:30:09,452 DEBUG   HandlerThread:93883 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:30:10,374 ERROR   SenderThread:93883 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 17:30:10,374 ERROR   SenderThread:93883 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 17:30:14,453 DEBUG   HandlerThread:93883 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:30:18,778 ERROR   SenderThread:93883 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 17:30:18,778 ERROR   SenderThread:93883 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 17:30:19,454 DEBUG   HandlerThread:93883 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:30:24,455 DEBUG   HandlerThread:93883 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:30:29,457 DEBUG   HandlerThread:93883 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:30:34,458 DEBUG   HandlerThread:93883 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:30:36,506 ERROR   SenderThread:93883 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 17:30:36,506 ERROR   SenderThread:93883 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 17:30:39,459 DEBUG   HandlerThread:93883 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:30:44,460 DEBUG   HandlerThread:93883 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:30:49,461 DEBUG   HandlerThread:93883 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:30:54,464 DEBUG   HandlerThread:93883 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:30:59,465 DEBUG   HandlerThread:93883 [handler.py:handle_request():144] handle_request: cancel
2024-05-02 17:30:59,465 DEBUG   SenderThread:93883 [sender.py:send():343] Record cancelled: run
2024-05-02 17:30:59,466 DEBUG   HandlerThread:93883 [handler.py:handle_request():144] handle_request: cancel
2024-05-02 17:30:59,466 DEBUG   HandlerThread:93883 [handler.py:handle_request():144] handle_request: status_report
2024-05-02 17:31:01,868 DEBUG   HandlerThread:93883 [handler.py:handle_request():144] handle_request: shutdown
2024-05-02 17:31:01,868 INFO    HandlerThread:93883 [handler.py:finish():841] shutting down handler
2024-05-02 17:31:02,467 INFO    SenderThread:93883 [sender.py:finish():1491] shutting down sender
2024-05-02 17:31:02,467 INFO    WriterThread:93883 [datastore.py:close():299] close: /root/Project-Build-an-ML-Pipeline-Starter/src/data_check/wandb/run-20240502_172959-4ylu9rl0/run-4ylu9rl0.wandb
